workspace:
  base: /go
  path: src/github.com/justinbarrick/fluxcloud

pipeline:
  build:
    image: golang:1.10-alpine
    commands:
      - apk update && apk add make git
      - make test
      - make build
    when:
      event: [push,tag]

  publish:
    image: plugins/docker
    secrets: [ DOCKER_USERNAME, DOCKER_PASSWORD ]
    repo: justinbarrick/fluxcloud
    tags:
      - latest
      - ${DRONE_TAG}
    when:
      event: tag
      branch: master

  slack:
    image: plugins/slack
    webhook: https://hooks.slack.com/services/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
    channel: '#kubernetes'
    username: Drone CI
    icon_url: https://i.imgur.com/B7Tk2Xf.png
    when:
      status: [success, failure]
      event: [push,tag]
    template: >
      {{#success build.status}}
        Build <{{build.link}}|#{{build.number}}> for <https://github.com/{{repo.owner}}/{{repo.name}}/tree/{{build.commit}}|{{repo.name}}#{{build.branch}}> by {{build.author}} succeeded!
      {{else}}
        Build <{{build.link}}|#{{build.number}}> for <https://github.com/{{repo.owner}}/{{repo.name}}/tree/{{build.commit}}|{{repo.name}}#{{build.branch}}> by {{build.author}} failed.
      {{/success}}

  slack2:
    image: plugins/slack
    webhook: https://hooks.slack.com/services/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
    channel: '#kubernetes'
    username: Drone CI Docker Push
    icon_url: https://i.imgur.com/B7Tk2Xf.png
    when:
      branch: master
      event: tag
    template: >
      Pushed <https://hub.docker.com/r/{{repo.owner}}/{{repo.name}}|{{repo.owner}}/{{repo.name}}:${DRONE_TAG}> to Dockerhub.
