---
kind: Service
apiVersion: v1
metadata:
  name: fluxcloud
spec:
  selector:
    name: fluxcloud
  ports:
  - protocol: TCP
    port: 80
    targetPort: 3031
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: fluxcloud
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        name: fluxcloud
    spec:
      containers:
      - name: fluxcloud
        image: justinbarrick/fluxcloud:master-a6c7844
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 3031
        env:
        - name: SLACK_URL
          value: "https://hooks.slack.com/services/WEBHOOK_URL"
        - name: SLACK_CHANNEL
          value: "#kubernetes"
        - name: SLACK_USERNAME
          value: Flux Deployer
        - name: SLACK_ICON_EMOJI
          value: ":heart:"
        - name: GITHUB_URL
          value: "https://github.com/justinbarrick/fluxcloud/"
